# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :release_testflight do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_options: {
        provisioningProfiles: {
          # "com.bundle.id" => "Provisioning Profileの名前"
          "com.yumeguri.techou" => "YumeguriTechou_Distribution"
        }
      }
    )
    api_key = app_store_connect_api_key(
      key_id: 'CRK47YJPY8',
      issuer_id: 'ca4103ed-4517-42cd-af8f-dfd2b55d1b19',
      key_filepath: './fastlane/AuthKey_CRK47YJPY8.p8'
    )
    upload_to_testflight(api_key: api_key)
  end
end
